// Generated by CoffeeScript 1.12.2

/*
AppVeyor API URL
 */

(function() {
  module.exports = typeof process !== "undefined" && process !== null ? process.env.APPVEYOR_API_URL : void 0;

}).call(this);
