// Generated by CoffeeScript 1.12.2

/*
Report test results to AppVeyor
 */

(function() {
  var events, path, post;

  path = require('path');

  post = require('./post');

  events = {
    pending: 'Ignored',
    pass: 'Passed',
    fail: 'Failed'
  };

  module.exports = function(runner) {
    var k, results, v;
    results = [];
    for (k in events) {
      v = events[k];
      results.push((function(v) {
        return runner.on(k, function(test) {
          var ref, ref1;
          return post({
            testFramework: 'mocha',
            testName: test.fullTitle(),
            fileName: path.relative('', test.file),
            outcome: v,
            durationMilliseconds: test.duration,
            ErrorMessage: (ref = test.err) != null ? ref.message : void 0,
            ErrorStackTrace: (ref1 = test.err) != null ? ref1.stack : void 0
          }, '/api/tests');
        });
      })(v));
    }
    return results;
  };

}).call(this);
