// Generated by CoffeeScript 1.12.2

/*
Message to AppVeyor
 */

(function() {
  var exports, message, post;

  exports = require('./');

  post = require('./post');

  exports.message = message = function(msg, details) {
    return post({
      category: 'info',
      message: msg,
      details: details
    }, '/api/build/messages');
  };

  exports.log = function(msg, details) {
    console.log(msg);
    return message(msg, details);
  };

}).call(this);
