// Generated by CoffeeScript 1.12.2

/*
Patch mocha
 */

(function() {
  var R, emit, listen;

  R = require('mocha').Runner;

  listen = require('./listen');

  emit = R.prototype.emit;

  R.prototype.emit = function() {
    delete R.prototype.emit;
    listen(this);
    return emit.apply(this, arguments);
  };

}).call(this);
